# Generated by Django 5.2.5 on 2025-08-26 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scholarship_name", models.CharField(max_length=255)),
                ("sponsor", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Government", "Government"),
                            ("Corporate", "Corporate"),
                            ("NGO", "NGO"),
                            ("Private/Foundation", "Private/Foundation"),
                            ("University", "University"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Undergraduate", "Undergraduate"),
                            ("Postgraduate", "Postgraduate"),
                            ("Vocational", "Vocational"),
                            (
                                "Undergraduate & Postgraduate",
                                "Undergraduate & Postgraduate",
                            ),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("eligibility_requirements", models.JSONField(default=list)),
                ("benefits", models.JSONField(default=list)),
                ("application_process", models.JSONField(default=list)),
                (
                    "website_or_contact",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("amount", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "application_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
