# Generated by Django 5.2.5 on 2025-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("JHS", "Junior High School"),
                    ("SHS", "Senior High School"),
                    ("UNI", "University"),
                    ("OTH", "Other"),
                ],
                default="OTH",
                max_length=10,
            ),
        ),
    ]
