# Generated by Django 5.2.5 on 2025-09-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_remove_user_date_of_birth_remove_user_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
    ]
