# Generated by Django 5.2.5 on 2025-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="residency",
            field=models.CharField(
                choices=[("Day", "Day"), ("Boarding", "Boarding")],
                default="Boarding",
                max_length=20,
            ),
        ),
    ]
