# Generated by Django 5.2.5 on 2025-08-26 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("founded", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "contact_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("contact_website", models.URLField(blank=True, null=True)),
                ("national_rank", models.IntegerField(blank=True, null=True)),
                ("total_students", models.IntegerField(blank=True, null=True)),
                (
                    "student_to_faculty_ratio",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                (
                    "domestic_undergraduate_min",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "domestic_undergraduate_max",
                    models.IntegerField(blank=True, null=True),
                ),
                ("domestic_currency", models.CharField(default="GHS", max_length=10)),
                (
                    "international_undergraduate_min",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "international_undergraduate_max",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "international_currency",
                    models.CharField(default="USD", max_length=10),
                ),
                ("accommodation_min", models.IntegerField(blank=True, null=True)),
                ("accommodation_max", models.IntegerField(blank=True, null=True)),
                (
                    "accommodation_currency",
                    models.CharField(default="GHS", max_length=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cutoff_points", models.CharField(default="15", max_length=50)),
                (
                    "requirements",
                    models.CharField(default="Standard requirements", max_length=255),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="universities.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "universities",
                    models.ManyToManyField(
                        related_name="facilities", to="universities.university"
                    ),
                ),
            ],
        ),
    ]
