# Generated by Django 5.2.5 on 2025-09-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("Past Questions", "Past Questions"),
                    ("Lecture Notes", "Lecture Notes"),
                    ("Assignments", "Assignments"),
                ],
                max_length=50,
            ),
        ),
    ]
